//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableBill
    {
        public int Id { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string CreditCardNumber { get; set; }
        public string CardType { get; set; }
        public Nullable<double> Amount { get; set; }
        public string DateOfTransaction { get; set; }
    }
}
